var g,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ea=function(a){if(a){for(var b=da,c=["WeakMap"],d=0;d<c.length-1;d++){var e=c[d];e in b||(b[e]=
{});b=b[e]}c=c[c.length-1];d=b[c];a=a(d);a!=d&&null!=a&&ca(b,c,{configurable:!0,writable:!0,value:a})}};
ea(function(a){function b(){}function c(a){ba(a,e)||ca(a,e,{value:new b})}function d(a){var d=Object[a];d&&(Object[a]=function(a){if(a instanceof b)return a;c(a);return d(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d["delete"](b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(k){return!1}}())return a;var e="$jscomp_hidden_"+Math.random();d("freeze");d("preventExtensions");d("seal");var f=0,h=
function(a){this.u=(f+=Math.random()+1).toString();if(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];for(a=b?b.call(a):{next:aa(a)};!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};h.prototype.set=function(a,b){c(a);if(!ba(a,e))throw Error("WeakMap key fail: "+a);a[e][this.u]=b;return this};h.prototype.get=function(a){return ba(a,e)?a[e][this.u]:void 0};h.prototype.has=function(a){return ba(a,e)&&ba(a[e],this.u)};h.prototype["delete"]=function(a){return ba(a,e)&&ba(a[e],
this.u)?delete a[e][this.u]:!1};return h});
var fa=fa||{},m=this,n=function(a){return void 0!==a},r=function(a){return"string"==typeof a},ha=function(a){return"number"==typeof a},ja=function(a,b,c){a=a.split(".");c=c||m;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&n(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}},ka=function(a,b){a=a.split(".");b=b||m;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b},la=function(){},t=function(a){var b=typeof a;
if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},u=function(a){return"array"==t(a)},ma=function(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length},v=function(a){return"function"==t(a)},w=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},pa=function(a){return a[na]||(a[na]=++oa)},na="closure_uid_"+(1E9*Math.random()>>>0),oa=0,qa=function(a,b,c){return a.call.apply(a.bind,arguments)},ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=
Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?qa:ra;return x.apply(null,arguments)},sa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},ta=
Date.now||function(){return+new Date},y=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Id=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var z=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};y(z,Error);z.prototype.name="CustomError";var ua;var va=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");z.call(this,c+a[d])};y(va,z);va.prototype.name="AssertionError";
var wa=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new va(""+e,f||[]);},A=function(a,b,c){a||wa("",null,b,Array.prototype.slice.call(arguments,2));return a},B=function(a,b){throw new va("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},xa=function(a,b,c){ha(a)||wa("Expected number but got %s: %s.",[t(a),a],b,Array.prototype.slice.call(arguments,2));return a},ya=function(a,b,c){v(a)||wa("Expected function but got %s: %s.",[t(a),
a],b,Array.prototype.slice.call(arguments,2))};var za=Array.prototype.indexOf?function(a,b){A(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(r(a))return r(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Aa=Array.prototype.forEach?function(a,b,c){A(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ba=Array.prototype.map?function(a,b){A(null!=a.length);return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=r(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},Ca=Array.prototype.some?function(a,b){A(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},Ea=function(a){a:{var b=Da;for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?
null:r(a)?a.charAt(b):a[b]},Ga=function(a,b){b=za(a,b);var c;if(c=0<=b)A(null!=a.length),Array.prototype.splice.call(a,b,1);return c},Ha=function(a){return Array.prototype.concat.apply([],arguments)},Ia=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ka=function(a,b){a.sort(b||Ja)},Ja=function(a,b){return a>b?1:a<b?-1:0};var La=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ma=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1},Na=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Pa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Oa.length;f++)c=Oa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Qa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ya=function(a){if(!Ra.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Sa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ta,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ua,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Va,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Wa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Xa,"&#0;"));return a},Sa=/&/g,Ta=/</g,Ua=/>/g,Va=/"/g,Wa=/'/g,Xa=/\x00/g,Ra=
/[\x00&<>"']/,Za={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},$a={"'":"\\'"},ab=function(a){a=String(a);for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=c+1,h;if(!(h=Za[d])){if(!(31<e&&127>e))if(d in $a)d=$a[d];else if(d in Za)d=$a[d]=Za[d];else{h=d.charCodeAt(0);if(31<h&&127>h)e=d;else{if(256>h){if(e="\\x",16>h||256<h)e+="0"}else e="\\u",4096>h&&(e+="0");e+=h.toString(16).toUpperCase()}d=$a[d]=e}h=d}b[f]=
h}b.push('"');return b.join("")},bb=function(a,b){return a<b?-1:a>b?1:0},cb=function(a){isFinite(a)&&(a=String(a));return r(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};var db=function(a,b){this.Zb=a.name||null;this.xc=a.Jd;this.Y={};for(a=0;a<b.length;a++){var c=b[a];this.Y[c.V]=c}};db.prototype.getName=function(){return this.Zb};db.prototype.va=function(){return this.xc?this.xc.A():null};var eb=function(a){a=Na(a.Y);Ka(a,function(a,c){return a.V-c.V});return a};var fb=function(a,b,c){this.v=a;A(!/[^0-9]/.test(b));this.V=b;this.Zb=c.name;this.Wb=!!c.Md;this.ca=c.Qb;this.$b=c.type};fb.prototype.va=function(){return this.v.prototype.A()};fb.prototype.getName=function(){return this.Zb};var gb=function(){this.J={};this.Y=this.A().Y;this.K=this.Mc=null},hb=function(a,b,c){c=c||a;for(var d in a.J){var e=Number(d);a.Y[e]||b.call(c,e,a.J[d])}};g=gb.prototype;g.has=function(a){A(a.va()==this.A(),"The current message does not contain the given field");return null!=this.J[a.V]};
g.get=function(a,b){A(a.va()==this.A(),"The current message does not contain the given field");var c=a.V;a=ib(this,c);this.Y[c].Wb?(b=b||0,A(0<=b&&b<a.length,"Given index %s is out of bounds.  Repeated field length: %s",b,a.length),b=a[b]):b=a;return b};g.set=function(a,b){A(a.va()==this.A(),"The current message does not contain the given field");C(this,a.V,b)};g.add=function(a,b){A(a.va()==this.A(),"The current message does not contain the given field");jb(this,a.V,b)};
g.clear=function(a){A(a.va()==this.A(),"The current message does not contain the given field");a=a.V;delete this.J[a];this.K&&delete this.K[a]};
var kb=function(a,b){A(a.constructor==b.constructor,"The source message must have the same type.");for(var c=eb(a.A()),d=0;d<c.length;d++){var e=c[d],f=e.V;if(null!=b.J[f]){a.K&&delete a.K[e.V];var h=11==e.ca||10==e.ca;if(e.Wb){e=ib(b,f)||[];for(var l=0;l<e.length;l++)jb(a,f,h?e[l].clone():e[l])}else e=ib(b,f),h?(h=ib(a,f))?kb(h,e):C(a,f,e.clone()):C(a,f,e)}}};
gb.prototype.clone=function(){var a=new this.constructor;A(a.constructor==this.constructor,"The source message must have the same type.");a!=this&&(a.J={},a.K&&(a.K={}),kb(a,this));return a};
var ib=function(a,b){var c=a.J[b];return null==c?null:a.Mc?b in a.K?a.K[b]:(c=a.Mc.Kd(a,a.Y[b],c),a.K[b]=c):c},C=function(a,b,c){var d=a.Y[b];14==d.ca?xa(c):A(Object(c).constructor==d.$b);a.J[b]=c;a.K&&(a.K[b]=c)},jb=function(a,b,c){var d=a.Y[b];14==d.ca?xa(c):A(Object(c).constructor==d.$b);a.J[b]||(a.J[b]=[]);a.J[b].push(c);a.K&&delete a.K[b]},lb=function(a,b){var c=[],d=b[0],e;for(e in b)0!=e&&c.push(new fb(a,e,b[e]));return new db(d,c)};var D=function(){gb.call(this)};y(D,gb);var mb=null,nb=function(){gb.call(this)};y(nb,gb);var ob=null;D.prototype.A=function(){var a=mb;a||(mb=a=lb(D,{0:{name:"Version",pd:"buzz.channel.Version"},1:{name:"major_version",Qb:5,type:Number},2:{name:"minor_version",Qb:5,type:Number}}));return a};D.A=D.prototype.A;nb.prototype.A=function(){var a=ob;a||(ob=a=lb(nb,{0:{name:"ProtocolVersion",pd:"buzz.channel.ProtocolVersion"},1:{name:"version",Qb:11,type:D}}));return a};nb.A=nb.prototype.A;var E;a:{var pb=m.navigator;if(pb){var qb=pb.userAgent;if(qb){E=qb;break a}}E=""}var F=function(a){return-1!=E.indexOf(a)};var rb=function(a){rb[" "](a);return a};rb[" "]=la;var sb=function(a,b){try{return rb(a[b]),!0}catch(c){}return!1},ub=function(a,b){var c=tb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var vb=F("Opera"),G=F("Trident")||F("MSIE"),wb=F("Edge"),xb=F("Gecko")&&!(-1!=E.toLowerCase().indexOf("webkit")&&!F("Edge"))&&!(F("Trident")||F("MSIE"))&&!F("Edge"),yb=-1!=E.toLowerCase().indexOf("webkit")&&!F("Edge"),zb=F("Macintosh"),Ab=F("Windows"),Bb=F("Android"),Cb=F("iPhone")&&!F("iPod")&&!F("iPad"),Db=F("iPad"),Eb=F("iPod"),Fb=function(){var a=m.document;return a?a.documentMode:void 0},Gb;
a:{var Hb="",Ib=function(){var a=E;if(xb)return/rv:([^\);]+)(\)|;)/.exec(a);if(wb)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(yb)return/WebKit\/(\S+)/.exec(a);if(vb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ib&&(Hb=Ib?Ib[1]:"");if(G){var Jb=Fb();if(null!=Jb&&Jb>parseFloat(Hb)){Gb=String(Jb);break a}}Gb=Hb}
var Kb=Gb,tb={},Lb=function(a){return ub(a,function(){for(var b=0,c=Qa(String(Kb)).split("."),d=Qa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",l=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];if(0==h[0].length&&0==l[0].length)break;b=bb(0==h[1].length?0:parseInt(h[1],10),0==l[1].length?0:parseInt(l[1],10))||bb(0==h[2].length,0==l[2].length)||bb(h[2],l[2]);h=h[3];l=l[3]}while(0==b)}return 0<=b})},Mb;var Nb=m.document;
Mb=Nb&&G?Fb()||("CSS1Compat"==Nb.compatMode?parseInt(Kb,10):5):void 0;var Ob={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var Rb=function(a,b){this.lc=a===Pb&&b||"";this.cd=Qb};Rb.prototype.xa=!0;Rb.prototype.ea=function(){return this.lc};Rb.prototype.toString=function(){return"Const{"+this.lc+"}"};var Sb=function(a){if(a instanceof Rb&&a.constructor===Rb&&a.cd===Qb)return a.lc;B("expected object of type Const, got '"+a+"'");return"type_error:Const"},Qb={},Pb={};var Ub=function(){this.ec="";this.dd=Tb};g=Ub.prototype;g.xa=!0;g.ea=function(){return this.ec};g.Sb=!0;g.Sa=function(){return 1};g.toString=function(){return"TrustedResourceUrl{"+this.ec+"}"};var Tb={};var Wb=function(){this.ga="";this.bd=Vb};g=Wb.prototype;g.xa=!0;g.ea=function(){return this.ga};g.Sb=!0;g.Sa=function(){return 1};g.toString=function(){return"SafeUrl{"+this.ga+"}"};
var Xb=function(a){if(a instanceof Wb&&a.constructor===Wb&&a.bd===Vb)return a.ga;B("expected object of type SafeUrl, got '"+a+"' of type "+t(a));return"type_error:SafeUrl"},Yb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,$b=function(a){if(a instanceof Wb)return a;a="object"==typeof a&&a.xa?a.ea():String(a);Yb.test(a)||(a="about:invalid#zClosurez");return Zb(a)},Vb={},Zb=function(a){var b=new Wb;b.ga=a;return b};Zb("about:blank");var H=function(){this.vb="";this.ad=ac};H.prototype.xa=!0;var ac={};H.prototype.ea=function(){return this.vb};H.prototype.toString=function(){return"SafeStyle{"+this.vb+"}"};H.prototype.rb=function(a){this.vb=a;return this};
var bc=(new H).rb(""),dc=function(a){if(a instanceof Wb)return'url("'+Xb(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';a=a instanceof Rb?Sb(a):cc(String(a));A(!/[{;}]/.test(a),"Value does not allow [{;}].");return a},cc=function(a){var b=a.replace(ec,"$1").replace(ec,"$1").replace(fc,"url");if(gc.test(b)){if(hc.test(a))return B("String value disallows comments, got: "+a),"zClosurez";for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==e&&b&&(c=!c)}if(!b||!c)return B("String value requires balanced quotes, got: "+
a),"zClosurez";if(!ic(a))return B("String value requires balanced square brackets and one identifier per pair of brackets, got: "+a),"zClosurez"}else return B("String value allows only [-,.\"'%_!# a-zA-Z0-9\\[\\]] and simple functions, got: "+a),"zClosurez";return jc(a)},ic=function(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&!c.test(e))return!1}return b},gc=/^[-,."'%_!# a-zA-Z0-9\[\]]+$/,fc=
/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,ec=/\b(hsl|hsla|rgb|rgba|matrix|calc|minmax|fit-content|repeat|(rotate|scale|translate)(X|Y|Z|3d)?)\([-+*/0-9a-z.%\[\], ]+\)/g,hc=/\/\*/,jc=function(a){return a.replace(fc,function(a,c,d,e){var b="";d=d.replace(/^(['"])(.*)\1$/,function(a,c,d){b=c;return d});a=$b(d).ea();return c+b+a+b+e})};var lc=function(){this.ga="";this.$c=kc;this.Cc=null};g=lc.prototype;g.Sb=!0;g.Sa=function(){return this.Cc};g.xa=!0;g.ea=function(){return this.ga};g.toString=function(){return"SafeHtml{"+this.ga+"}"};
var mc=function(a){if(a instanceof lc&&a.constructor===lc&&a.$c===kc)return a.ga;B("expected object of type SafeHtml, got '"+a+"' of type "+t(a));return"type_error:SafeHtml"},nc=/^[a-zA-Z0-9-]+$/,oc={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},qc=function(a){var b=0,c="",d=function(a){if(u(a))Aa(a,d);else{if(!(a instanceof lc)){var e="object"==typeof a,h=null;e&&a.Sb&&(h=a.Sa());a=pc(Ya(e&&a.xa?a.ea():String(a)),h)}c+=mc(a);a=a.Sa();0==b?b=a:0!=a&&b!=a&&(b=null)}};
Aa(arguments,d);return pc(c,b)},kc={},pc=function(a,b){return(new lc).rb(a,b)};lc.prototype.rb=function(a,b){this.ga=a;this.Cc=b;return this};pc("<!DOCTYPE html>",0);pc("",0);pc("<br>",0);var rc={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},sc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div");a.innerHTML="<div><div></div></div>";if(!a.firstChild)return!1;var b=a.firstChild.firstChild;a.innerHTML="";return!b.parentElement});var uc=function(a,b,c){function d(c){c&&b.appendChild(r(c)?a.createTextNode(c):c)}for(var e=1;e<c.length;e++){var f=c[e];!ma(f)||w(f)&&0<f.nodeType?d(f):Aa(tc(f)?Ia(f):f,d)}},vc=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null},tc=function(a){if(a&&"number"==typeof a.length){if(w(a))return"function"==typeof a.item||"string"==typeof a.item;if(v(a))return"function"==typeof a.item}return!1},wc=function(){this.Ra=m.document||document};g=wc.prototype;
g.getElementsByTagName=function(a,b){return(b||this.Ra).getElementsByTagName(String(a))};g.createElement=function(a){return this.Ra.createElement(String(a))};g.createTextNode=function(a){return this.Ra.createTextNode(String(a))};g.h=function(){var a=this.Ra;return a.parentWindow||a.defaultView};g.appendChild=function(a,b){A(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};
g.append=function(a,b){var c=a;A(c,"Node cannot be null or undefined.");uc(9==c.nodeType?c:c.ownerDocument||c.document,a,arguments)};g.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.removeNode=vc;g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var xc=function(){this.xb=void 0};xc.prototype.Ab=function(a){var b=[];yc(this,a,b);return b.join("")};
var yc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(u(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],yc(a,a.xb?a.xb.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),zc(d,c),c.push(":"),yc(a,a.xb?a.xb.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":zc(b,
c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},Ac={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Bc=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g,zc=function(a,b){b.push('"',a.replace(Bc,function(a){var b=Ac[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),
Ac[a]=b);return b}),'"')};var Cc=function(){};var Dc=function(a,b){this.Zc=!!b};y(Dc,Cc);Dc.prototype.Ab=function(a){var b=new Ec;Fc(this,a,b);return b.toString()};
var Fc=function(a,b,c){var d=eb(b.A());Aa(d,function(a){if(b.has(a)){A(a.va()==b.A(),"The current message does not contain the given field");var d=a.V;d=b.Y[d].Wb?null!=b.J[d]?b.J[d].length:0:null!=b.J[d]?1:0;for(var e=0;e<d;++e){c.append(a.getName());11==a.ca||10==a.ca?(c.append(" {"),Gc(c),c.na+=2):c.append(": ");Hc(this,b.get(a,e),a,c);if(11==a.ca||10==a.ca)Ic(c),c.append("}");Gc(c)}}},a);hb(b,function(a,b){Jc(this,a,b,A(c))},a)},Jc=function(a,b,c,d){if(null!=c)if(u(c))Aa(c,function(a){Jc(this,
b,a,d)},a);else{if(w(c)){d.append(b);d.append(" {");Gc(d);d.na+=2;if(c instanceof gb)Fc(a,c,d);else for(var e in c){var f=cb(e);A(isFinite(f)&&0==f%1);Jc(a,f,c[e],d)}Ic(d);d.append("}")}else r(c)&&(c=ab(c)),d.append(b),d.append(": "),d.append(c.toString());Gc(d)}},Hc=function(a,b,c,d){switch(c.ca){case 1:case 2:case 3:case 4:case 5:case 13:case 6:case 7:case 8:case 15:case 16:case 17:case 18:d.append(b);break;case 12:case 9:b=ab(b.toString());d.append(b);break;case 14:if(!a.Zc){var e=!1;La(c.$b,function(a,
c){e||a!=b||(d.append(c),e=!0)})}e&&!a.Zc||d.append(b.toString());break;case 10:case 11:Fc(a,b,d)}},Ec=function(){this.na=0;this.kb=[];this.gc=!0};Ec.prototype.toString=function(){return this.kb.join("")};var Ic=function(a){a.na-=2;A(0<=a.na)};Ec.prototype.append=function(a){if(this.gc){for(var b=0;b<this.na;++b)this.kb.push(" ");this.gc=!1}this.kb.push(a.toString())};var Gc=function(a){a.kb.push("\n");a.gc=!0};var Kc=Object.freeze||function(a){return a};var Lc=new Dc;gb.prototype.toString=function(){return Lc.Ab(this)};var Mc=function(){this.name="FINEST";this.value=300};Mc.prototype.toString=function(){return this.name};var Nc=new Mc;var Oc=function(a){var b=I.c;b&&b.log(Nc,a,void 0)},J=function(a,b){a&&a.Nd(b,void 0)},K=function(a){var b=I.c;b&&b.info(a,void 0)},L=function(a,b){a&&a.Ld(b,void 0)};var M=function(){this.la=this.la;this.za=this.za};M.prototype.la=!1;M.prototype.Mb=function(){this.la||(this.la=!0,this.f())};var Pc=function(a,b){a.la?n(void 0)?b.call(void 0):b():(a.za||(a.za=[]),a.za.push(n(void 0)?x(b,void 0):b))};M.prototype.f=function(){if(this.za)for(;this.za.length;)this.za.shift()()};var N=function(a){a&&"function"==typeof a.Mb&&a.Mb()};var Qc=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Ca=!1;this.Xc=!0};Qc.prototype.stopPropagation=function(){this.Ca=!0};Qc.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Xc=!1};var Rc;(Rc=!G)||(Rc=9<=Number(Mb));var Sc=Rc,Tc=G&&!Lb("9"),Uc=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",la,b),m.removeEventListener("test",la,b)}catch(c){}return a}();var Vc=function(a,b){Qc.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.ma=null;a&&this.Ub(a,b)};y(Vc,Qc);var Wc=Kc({2:"touch",3:"pen",4:"mouse"});
Vc.prototype.Ub=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;(b=a.relatedTarget)?xb&&(sb(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.offsetX=yb||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=yb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:
a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=r(a.pointerType)?a.pointerType:
Wc[a.pointerType]||"";this.state=a.state;this.ma=a;a.defaultPrevented&&this.preventDefault()};Vc.prototype.stopPropagation=function(){Vc.H.stopPropagation.call(this);this.ma.stopPropagation?this.ma.stopPropagation():this.ma.cancelBubble=!0};Vc.prototype.preventDefault=function(){Vc.H.preventDefault.call(this);var a=this.ma;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Tc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Xc="closure_listenable_"+(1E6*Math.random()|0),Yc=function(a){return!(!a||!a[Xc])},Zc=0;var $c=function(a,b,c,d,e){this.listener=a;this.wb=null;this.src=b;this.type=c;this.capture=!!d;this.wa=e;this.key=++Zc;this.Pa=this.lb=!1},ad=function(a){a.Pa=!0;a.listener=null;a.wb=null;a.src=null;a.wa=null};var bd=function(a){this.src=a;this.B={};this.gb=0};bd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.B[f];a||(a=this.B[f]=[],this.gb++);var h=cd(a,b,d,e);-1<h?(b=a[h],c||(b.lb=!1)):(b=new $c(b,this.src,f,!!d,e),b.lb=c,a.push(b));return b};bd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.B))return!1;var e=this.B[a];b=cd(e,b,c,d);return-1<b?(ad(e[b]),A(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.B[a],this.gb--),!0):!1};
var dd=function(a,b){var c=b.type;c in a.B&&Ga(a.B[c],b)&&(ad(b),0==a.B[c].length&&(delete a.B[c],a.gb--))};bd.prototype.ab=function(a){a=a&&a.toString();var b=0,c;for(c in this.B)if(!a||c==a){for(var d=this.B[c],e=0;e<d.length;e++)++b,ad(d[e]);delete this.B[c];this.gb--}};bd.prototype.Ta=function(a,b,c,d){a=this.B[a.toString()];var e=-1;a&&(e=cd(a,b,c,d));return-1<e?a[e]:null};
bd.prototype.hasListener=function(a,b){var c=n(a),d=c?a.toString():"",e=n(b);return Ma(this.B,function(a){for(var f=0;f<a.length;++f)if(!(c&&a[f].type!=d||e&&a[f].capture!=b))return!0;return!1})};var cd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Pa&&f.listener==b&&f.capture==!!c&&f.wa==d)return e}return-1};var ed="closure_lm_"+(1E6*Math.random()|0),fd={},gd=0,id=function(a,b,c,d,e){if(d&&d.once)return hd(a,b,c,d,e);if(u(b)){for(var f=0;f<b.length;f++)id(a,b[f],c,d,e);return null}c=jd(c);return Yc(a)?a.Xa(b,c,w(d)?!!d.capture:!!d,e):kd(a,b,c,!1,d,e)},kd=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=w(e)?!!e.capture:!!e,l=ld(a);l||(a[ed]=l=new bd(a));c=l.add(b,c,d,h,f);if(c.wb)return c;d=md();c.wb=d;d.src=a;d.listener=c;if(a.addEventListener)Uc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(nd(b.toString()),d);else if(a.addListener&&a.removeListener)A("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");gd++;return c},md=function(){var a=od,b=Sc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},hd=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)hd(a,b[f],c,d,e);return null}c=jd(c);return Yc(a)?
a.Xb(b,c,w(d)?!!d.capture:!!d,e):kd(a,b,c,!0,d,e)},pd=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)pd(a,b[f],c,d,e);else d=w(d)?!!d.capture:!!d,c=jd(c),Yc(a)?a.mc(b,c,d,e):a&&(a=ld(a))&&(b=a.Ta(b,c,d,e))&&qd(b)},qd=function(a){if(!ha(a)&&a&&!a.Pa){var b=a.src;if(Yc(b))dd(b.S,a);else{var c=a.type,d=a.wb;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(nd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);gd--;(c=ld(b))?(dd(c,a),0==c.gb&&(c.src=
null,b[ed]=null)):ad(a)}}},rd=function(a,b,c,d,e){c=jd(c);d=!!d;return Yc(a)?a.Ta(b,c,d,e):a?(a=ld(a))?a.Ta(b,c,d,e):null:null},nd=function(a){return a in fd?fd[a]:fd[a]="on"+a},td=function(a,b,c,d){var e=!0;if(a=ld(a))if(b=a.B[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.Pa&&(f=sd(f,d),e=e&&!1!==f)}return e},sd=function(a,b){var c=a.listener,d=a.wa||a.src;a.lb&&qd(a);return c.call(d,b)},od=function(a,b){if(a.Pa)return!0;if(!Sc){var c=b||ka("window.event");b=new Vc(c,
this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.currentTarget;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.Ca&&0<=e;e--){b.currentTarget=c[e];var f=td(c[e],a,!0,b);d=d&&f}for(e=0;!b.Ca&&e<c.length;e++)b.currentTarget=c[e],f=td(c[e],a,!1,b),d=d&&f}return d}return sd(a,new Vc(b,this))},ld=function(a){a=a[ed];return a instanceof bd?a:null},ud="__closure_events_fn_"+
(1E9*Math.random()>>>0),jd=function(a){A(a,"Listener can not be null.");if(v(a))return a;A(a.handleEvent,"An object listener must have handleEvent method.");a[ud]||(a[ud]=function(b){return a.handleEvent(b)});return a[ud]};var O=function(){M.call(this);this.S=new bd(this);this.ed=this;this.cc=null};y(O,M);O.prototype[Xc]=!0;g=O.prototype;g.addEventListener=function(a,b,c,d){id(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){pd(this,a,b,c,d)};
g.dispatchEvent=function(a){vd(this);var b=this.cc;if(b){var c=[];for(var d=1;b;b=b.cc)c.push(b),A(1E3>++d,"infinite loop")}b=this.ed;d=a.type||a;if(r(a))a=new Qc(a,b);else if(a instanceof Qc)a.target=a.target||b;else{var e=a;a=new Qc(d,b);Pa(a,e)}e=!0;if(c)for(var f=c.length-1;!a.Ca&&0<=f;f--){var h=a.currentTarget=c[f];e=wd(h,d,!0,a)&&e}a.Ca||(h=a.currentTarget=b,e=wd(h,d,!0,a)&&e,a.Ca||(e=wd(h,d,!1,a)&&e));if(c)for(f=0;!a.Ca&&f<c.length;f++)h=a.currentTarget=c[f],e=wd(h,d,!1,a)&&e;return e};
g.f=function(){O.H.f.call(this);this.S&&this.S.ab(void 0);this.cc=null};g.Xa=function(a,b,c,d){vd(this);return this.S.add(String(a),b,!1,c,d)};g.Xb=function(a,b,c,d){return this.S.add(String(a),b,!0,c,d)};g.mc=function(a,b,c,d){this.S.remove(String(a),b,c,d)};var wd=function(a,b,c,d){b=a.S.B[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.Pa&&h.capture==c){var l=h.listener,q=h.wa||h.src;h.lb&&dd(a.S,h);e=!1!==l.call(q,d)&&e}}return e&&0!=d.Xc};
O.prototype.Ta=function(a,b,c,d){return this.S.Ta(String(a),b,c,d)};O.prototype.hasListener=function(a,b){return this.S.hasListener(n(a)?String(a):void 0,b)};var vd=function(a){A(a.S,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var xd=function(a,b){this.ud=100;this.kd=a;this.Ad=b;this.tb=0;this.pb=null};xd.prototype.get=function(){if(0<this.tb){this.tb--;var a=this.pb;this.pb=a.next;a.next=null}else a=this.kd();return a};xd.prototype.put=function(a){this.Ad(a);this.tb<this.ud&&(this.tb++,a.next=this.pb,this.pb=a)};var yd=function(a){m.setTimeout(function(){throw a;},0)},zd,Ad=function(){var a=m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!F("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;
a=x(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!F("Trident")&&!F("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(n(c.next)){c=c.next;var a=c.wc;c.wc=null;a()}};return function(a){d.next={wc:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?
function(a){var b=document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){m.setTimeout(a,0)}};var Bd=function(){this.Fb=this.Ea=null},Dd=new xd(function(){return new Cd},function(a){a.reset()});Bd.prototype.add=function(a,b){var c=Dd.get();c.set(a,b);this.Fb?this.Fb.next=c:(A(!this.Ea),this.Ea=c);this.Fb=c};Bd.prototype.remove=function(){var a=null;this.Ea&&(a=this.Ea,this.Ea=this.Ea.next,this.Ea||(this.Fb=null),a.next=null);return a};var Cd=function(){this.next=this.scope=this.Rb=null};Cd.prototype.set=function(a,b){this.Rb=a;this.scope=b;this.next=null};
Cd.prototype.reset=function(){this.next=this.scope=this.Rb=null};var Id=function(a,b){Ed||Fd();Gd||(Ed(),Gd=!0);Hd.add(a,b)},Ed,Fd=function(){if(m.Promise&&m.Promise.resolve){var a=m.Promise.resolve(void 0);Ed=function(){a.then(Jd)}}else Ed=function(){var a=Jd;!v(m.setImmediate)||m.Window&&m.Window.prototype&&!F("Edge")&&m.Window.prototype.setImmediate==m.setImmediate?(zd||(zd=Ad()),zd(a)):m.setImmediate(a)}},Gd=!1,Hd=new Bd,Jd=function(){for(var a;a=Hd.remove();){try{a.Rb.call(a.scope)}catch(b){yd(b)}Dd.put(a)}Gd=!1};var Kd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},Ld=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var P=function(a,b){this.l=0;this.ha=void 0;this.Ga=this.aa=this.v=null;this.ob=this.Pb=!1;if(a!=la)try{var c=this;a.call(b,function(a){Md(c,2,a)},function(a){if(!(a instanceof Nd))try{if(a instanceof Error)throw a;throw Error("Promise rejected.");}catch(e){}Md(c,3,a)})}catch(d){Md(this,3,d)}},Od=function(){this.next=this.context=this.Na=this.Aa=this.sa=null;this.ib=!1};Od.prototype.reset=function(){this.context=this.Na=this.Aa=this.sa=null;this.ib=!1};
var Pd=new xd(function(){return new Od},function(a){a.reset()}),Qd=function(a,b,c){var d=Pd.get();d.Aa=a;d.Na=b;d.context=c;return d};P.prototype.then=function(a,b,c){null!=a&&ya(a,"opt_onFulfilled should be a function.");null!=b&&ya(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return Rd(this,v(a)?a:null,v(b)?b:null,c)};Kd(P);P.prototype.cancel=function(a){0==this.l&&Id(function(){var b=new Nd(a);Sd(this,b)},this)};
var Sd=function(a,b){if(0==a.l)if(a.v){var c=a.v;if(c.aa){for(var d=0,e=null,f=null,h=c.aa;h&&(h.ib||(d++,h.sa==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.l&&1==d?Sd(c,b):(f?(d=f,A(c.aa),A(null!=d),d.next==c.Ga&&(c.Ga=d),d.next=d.next.next):Td(c),Ud(c,e,3,b)))}a.v=null}else Md(a,3,b)},Wd=function(a,b){a.aa||2!=a.l&&3!=a.l||Vd(a);A(null!=b.Aa);a.Ga?a.Ga.next=b:a.aa=b;a.Ga=b},Rd=function(a,b,c,d){var e=Qd(null,null,null);e.sa=new P(function(a,h){e.Aa=b?function(c){try{var e=b.call(d,c);a(e)}catch(p){h(p)}}:
a;e.Na=c?function(b){try{var e=c.call(d,b);!n(e)&&b instanceof Nd?h(b):a(e)}catch(p){h(p)}}:h});e.sa.v=a;Wd(a,e);return e.sa};P.prototype.Fd=function(a){A(1==this.l);this.l=0;Md(this,2,a)};P.prototype.Gd=function(a){A(1==this.l);this.l=0;Md(this,3,a)};
var Md=function(a,b,c){if(0==a.l){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.l=1;a:{var d=c,e=a.Fd,f=a.Gd;if(d instanceof P){null!=e&&ya(e,"opt_onFulfilled should be a function.");null!=f&&ya(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");Wd(d,Qd(e||la,f||null,a));var h=!0}else if(Ld(d))d.then(e,f,a),h=!0;else{if(w(d))try{var l=d.then;if(v(l)){Xd(d,l,e,f,a);h=!0;break a}}catch(q){f.call(a,q);h=!0;break a}h=!1}}h||
(a.ha=c,a.l=b,a.v=null,Vd(a),3!=b||c instanceof Nd||Zd(a,c))}},Xd=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},l=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,l)}catch(q){l(q)}},Vd=function(a){a.Pb||(a.Pb=!0,Id(a.od,a))},Td=function(a){var b=null;a.aa&&(b=a.aa,a.aa=b.next,b.next=null);a.aa||(a.Ga=null);null!=b&&A(null!=b.Aa);return b};P.prototype.od=function(){for(var a;a=Td(this);)Ud(this,a,this.l,this.ha);this.Pb=!1};
var Ud=function(a,b,c,d){if(3==c&&b.Na&&!b.ib)for(;a&&a.ob;a=a.v)a.ob=!1;if(b.sa)b.sa.v=null,$d(b,c,d);else try{b.ib?b.Aa.call(b.context):$d(b,c,d)}catch(e){ae.call(null,e)}Pd.put(b)},$d=function(a,b,c){2==b?a.Aa.call(a.context,c):a.Na&&a.Na.call(a.context,c)},Zd=function(a,b){a.ob=!0;Id(function(){a.ob&&ae.call(null,b)})},ae=yd,Nd=function(a){z.call(this,a)};y(Nd,z);Nd.prototype.name="cancel";var be=function(a,b){O.call(this);this.La=a||1;this.fb=b||m;this.uc=x(this.Ed,this);this.Lc=ta()};y(be,O);g=be.prototype;g.enabled=!1;g.W=null;g.setInterval=function(a){this.La=a;this.W&&this.enabled?(this.stop(),this.start()):this.W&&this.stop()};g.Ed=function(){if(this.enabled){var a=ta()-this.Lc;0<a&&a<.8*this.La?this.W=this.fb.setTimeout(this.uc,this.La-a):(this.W&&(this.fb.clearTimeout(this.W),this.W=null),this.dispatchEvent("tick"),this.enabled&&(this.stop(),this.start()))}};
g.start=function(){this.enabled=!0;this.W||(this.W=this.fb.setTimeout(this.uc,this.La),this.Lc=ta())};g.stop=function(){this.enabled=!1;this.W&&(this.fb.clearTimeout(this.W),this.W=null)};g.f=function(){be.H.f.call(this);this.stop();delete this.fb};var ce=function(a,b,c){if(v(a))c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:m.setTimeout(a,b||0)};var de=function(a,b,c){M.call(this);this.Yb=a;this.La=b||0;this.Ja=c;this.gd=x(this.nd,this)};y(de,M);g=de.prototype;g.u=0;g.f=function(){de.H.f.call(this);this.stop();delete this.Yb;delete this.Ja};g.start=function(a){this.stop();this.u=ce(this.gd,n(a)?a:this.La)};g.stop=function(){this.Vb()&&m.clearTimeout(this.u);this.u=0};g.Vb=function(){return 0!=this.u};g.nd=function(){this.u=0;this.Yb&&this.Yb.call(this.Ja)};var Q=function(a){M.call(this);this.Ja=a;this.g={}};y(Q,M);var ee=[];Q.prototype.Xa=function(a,b,c,d){u(b)||(b&&(ee[0]=b.toString()),b=ee);for(var e=0;e<b.length;e++){var f=id(a,b[e],c||this.handleEvent,d||!1,this.Ja||this);if(!f)break;this.g[f.key]=f}return this};Q.prototype.Xb=function(a,b,c,d){return fe(this,a,b,c,d)};var fe=function(a,b,c,d,e,f){if(u(c))for(var h=0;h<c.length;h++)fe(a,b,c[h],d,e,f);else{b=hd(b,c,d||a.handleEvent,e,f||a.Ja||a);if(!b)return a;a.g[b.key]=b}return a};
Q.prototype.mc=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.mc(a,b[f],c,d,e);else if(a=rd(a,b,c||this.handleEvent,w(d)?!!d.capture:!!d,e||this.Ja||this))qd(a),delete this.g[a.key]};Q.prototype.ab=function(){La(this.g,function(a,b){this.g.hasOwnProperty(b)&&qd(a)},this);this.g={}};Q.prototype.f=function(){Q.H.f.call(this);this.ab()};Q.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var ge="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""},he=function(){};he.prototype.next=function(){throw ge;};he.prototype.Ib=function(){return this};var ie=function(){M.call(this);this.ic={}};y(ie,M);ie.prototype.connect=function(a){a&&a()};ie.prototype.isConnected=function(){return!0};ie.prototype.f=function(){ie.H.f.call(this);delete this.ic;delete this.Bc};var I={};var je={1:"NativeMessagingTransport",2:"FrameElementMethodTransport",3:"IframeRelayTransport",4:"IframePollingTransport",5:"FlashTransport",6:"NixTransport",7:"DirectTransport"},ke=["pu","lru","pru","lpu","ppu"],R={},me=function(){for(var a=10,b=le,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},le="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var S=function(a){M.call(this);this.X=a||ua||(ua=new wc)};y(S,M);S.prototype.Qa=0;S.prototype.h=function(){return this.X.h()};S.prototype.getName=function(){return je[String(this.Qa)]||""};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var T=function(a,b){this.zb=[];this.Oc=a;this.Ac=b||null;this.Ua=this.N=!1;this.ha=void 0;this.kc=this.tc=this.Jb=!1;this.Db=0;this.v=null;this.jb=0};T.prototype.cancel=function(a){if(this.N)this.ha instanceof T&&this.ha.cancel();else{if(this.v){var b=this.v;delete this.v;a?b.cancel(a):(b.jb--,0>=b.jb&&b.cancel())}this.Oc?this.Oc.call(this.Ac,this):this.kc=!0;this.N||this.Dc(new ne(this))}};T.prototype.zc=function(a,b){this.Jb=!1;oe(this,a,b)};
var oe=function(a,b,c){a.N=!0;a.ha=c;a.Ua=!b;pe(a)},re=function(a){if(a.N){if(!a.kc)throw new qe(a);a.kc=!1}};T.prototype.M=function(a){re(this);se(a);oe(this,!0,a)};T.prototype.Dc=function(a){re(this);se(a);oe(this,!1,a)};var se=function(a){A(!(a instanceof T),"An execution sequence may not be initiated with a blocking Deferred.")},ue=function(a,b,c){te(a,b,null,c)},te=function(a,b,c,d){A(!a.tc,"Blocking Deferreds can not be re-used");a.zb.push([b,c,d]);a.N&&pe(a)};
T.prototype.then=function(a,b,c){var d,e,f=new P(function(a,b){d=a;e=b});te(this,d,function(a){a instanceof ne?f.cancel():e(a)});return f.then(a,b,c)};Kd(T);var ve=function(a,b){b instanceof T?ue(a,x(b.fd,b)):ue(a,function(){return b})};T.prototype.fd=function(a){var b=new T;te(this,b.M,b.Dc,b);a&&(b.v=this,this.jb++);return b};
var we=function(a){return Ca(a.zb,function(a){return v(a[1])})},pe=function(a){if(a.Db&&a.N&&we(a)){var b=a.Db,c=xe[b];c&&(m.clearTimeout(c.u),delete xe[b]);a.Db=0}a.v&&(a.v.jb--,delete a.v);b=a.ha;for(var d=c=!1;a.zb.length&&!a.Jb;){var e=a.zb.shift(),f=e[0],h=e[1];e=e[2];if(f=a.Ua?h:f)try{var l=f.call(e||a.Ac,b);n(l)&&(a.Ua=a.Ua&&(l==b||l instanceof Error),a.ha=b=l);if(Ld(b)||"function"===typeof m.Promise&&b instanceof m.Promise)d=!0,a.Jb=!0}catch(q){b=q,a.Ua=!0,we(a)||(c=!0)}}a.ha=b;d&&(l=x(a.zc,
a,!0),d=x(a.zc,a,!1),b instanceof T?(te(b,l,d),b.tc=!0):b.then(l,d));c&&(b=new ye(b),xe[b.u]=b,a.Db=b.u)},qe=function(){z.call(this)};y(qe,z);qe.prototype.message="Deferred has already fired";qe.prototype.name="AlreadyCalledError";var ne=function(){z.call(this)};y(ne,z);ne.prototype.message="Deferred was canceled";ne.prototype.name="CanceledError";var ye=function(a){this.u=m.setTimeout(x(this.Dd,this),0);this.nb=a};
ye.prototype.Dd=function(){A(xe[this.u],"Cannot throw an error that is not scheduled.");delete xe[this.u];throw this.nb;};var xe={};var Ae=function(a,b){S.call(this,b);this.a=a;this.Ia=new Q(this);Pc(this,sa(N,this.Ia));this.Z=new be(100,this.h());Pc(this,sa(N,this.Z));this.D=new T;this.F=new T;this.w=new T;this.Nb=me();this.pa=null;this.Fa={};this.xd=this.a.name;ze(this.a,this.a.name+"_"+U(this.a));this.Va=!1;ve(this.w,this.D);ve(this.w,this.F);ue(this.w,this.ac,this);this.w.M(!0);this.Ia.Xa(this.Z,"tick",this.Ya);K("DirectTransport created. role="+U(this.a))};y(Ae,S);
var Be={},Ee=function(a){var b=new Ce(a.channelName,a.service,a.payload);a=b.Kb;var c=b.hc;b=b.Za;L(I.c,"messageReceived: channel="+a+", service="+c+", payload="+b);var d=R[a];if(d)return d.ia(c,b),!0;d=De(b)[0];for(var e in R){var f=R[e];if(1==U(f)&&!f.isConnected()&&"tp"==c&&"SETUP"==d)return ze(f,a),f.ia(c,b),!0}K("channel name mismatch; message ignored.");return!1};g=Ae.prototype;g.Qa=7;
g.Cb=function(a){a=De(a);var b=a[1];switch(a[0]){case "SETUP_ACK":this.D.N||this.D.M(!0);break;case "SETUP":this.yb(),null!=this.pa&&this.pa!=b&&(K("Sending SETUP and changing peer ID to: "+b),this.bb()),this.pa=b}};g.bb=function(){this.send("tp","SETUP,"+this.Nb)};g.yb=function(){this.send("tp","SETUP_ACK");this.F.N||this.F.M(!0)};
g.connect=function(){var a=this.h();if(a){var b=pa(a);0==(Be[b]||0)&&null==ka("crosswindowmessaging.channel",a)&&ja("crosswindowmessaging.channel",Ee,a);Be[b]++;this.Va=!0;this.Ya()}else L(I.c,"connect(): no window to initialize.")};g.Ya=function(){this.a.isConnected()?this.Z.stop():(this.Z.start(),this.bb())};g.send=function(a,b){this.a.R?(a=new Ce(this.xd+"_"+(0==U(this.a)?1:0),a,b),this.a.m.directSyncMode?this.Ec(a):this.Fa[pa(a)]=ce(x(this.Ec,this,a),0)):L(I.c,"send(): window not ready")};
g.Ec=function(a){var b=pa(a);this.Fa[b]&&delete this.Fa[b];try{var c=ka("crosswindowmessaging.channel",this.a.R)}catch(d){(a=I.c)&&a.ra("Can't access other window, ignoring.",d);return}if(null===c)(a=I.c)&&a.ra("Peer window had no global function.",void 0);else try{c({channelName:a.Kb,service:a.hc,payload:a.Za}),K("send(): channelName="+a.Kb+" service="+a.hc+" payload="+a.Za)}catch(d){(a=I.c)&&a.ra("Error performing call, ignoring.",d)}};g.ac=function(){Fe(this.a,0)};
g.f=function(){if(this.Va){var a=this.h(),b=pa(a);1==--Be[b]&&ja("crosswindowmessaging.channel",null,a)}this.Fa&&(La(this.Fa,function(a){m.clearTimeout(a)}),this.Fa=null);this.D&&(this.D.cancel(),delete this.D);this.F&&(this.F.cancel(),delete this.F);this.w&&(this.w.cancel(),delete this.w);Ae.H.f.call(this)};var De=function(a){a=a.split(",");a[1]=a[1]||null;return a},Ce=function(a,b,c){this.Kb=a;this.hc=b;this.Za=c};var Ge=function(a,b){S.call(this,b);this.a=a;this.$a=[];this.ld=x(this.md,this)};y(Ge,S);g=Ge.prototype;g.Qa=2;g.fc=!1;g.connect=function(){0==U(this.a)?(this.fa=this.a.Ka,this.fa.XPC_toOuter=x(this.Jc,this)):this.rc()};
g.rc=function(){var a=!0;try{this.fa||(this.fa=this.h().frameElement),this.fa&&this.fa.XPC_toOuter&&(this.bc=this.fa.XPC_toOuter,this.fa.XPC_toOuter.XPC_toInner=x(this.Jc,this),a=!1,this.send("tp","SETUP_ACK"),Fe(this.a))}catch(b){J(I.c,"exception caught while attempting setup: "+b)}a&&(this.qc||(this.qc=x(this.rc,this)),this.h().setTimeout(this.qc,100))};
g.Cb=function(a){if(0!=U(this.a)||this.a.isConnected()||"SETUP_ACK"!=a)throw Error("Got unexpected transport message.");this.bc=this.fa.XPC_toOuter.XPC_toInner;Fe(this.a)};g.Jc=function(a,b){this.fc||0!=this.$a.length?(this.$a.push({Bd:a,Za:b}),1==this.$a.length&&this.h().setTimeout(this.ld,1)):this.a.ia(a,b)};g.md=function(){for(;this.$a.length;){var a=this.$a.shift();this.a.ia(a.Bd,a.Za)}};g.send=function(a,b){this.fc=!0;this.bc(a,b);this.fc=!1};
g.f=function(){Ge.H.f.call(this);this.fa=this.bc=null};var Ie=function(a,b){S.call(this,b);this.a=a;this.yd=this.a.m.pru;this.Sc=this.a.m.ifrid;yb&&He()};y(Ie,S);if(yb)var Je=[],Ke=0,He=function(){Ke||(Ke=window.setTimeout(function(){Le()},1E3))},Le=function(a){var b=ta();for(a=a||3E3;Je.length&&b-Je[0].timestamp>=a;){var c=Je.shift().sd;vc(c);Oc("iframe removed")}Ke=window.setTimeout(Me,1E3)},Me=function(){Le()};var Ne={};Ie.prototype.Qa=3;Ie.prototype.connect=function(){this.h().xpcRelay||(this.h().xpcRelay=Oe);this.send("tp","SETUP")};
var Oe=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c);b=b.substr(c+1);if(G&&-1!=(c=d.indexOf("|"))){h=d.substr(0,c);d=d.substr(c+1);c=d.indexOf("+");var e=d.substr(0,c);c=parseInt(d.substr(c+1),10);var f=Ne[e];f||(f=Ne[e]={Gc:[],Tc:0,Fc:0});-1!=d.indexOf("++")&&(f.Fc=c+1);f.Gc[c]=b;f.Tc++;if(f.Tc!=f.Fc)return;b=f.Gc.join("");delete Ne[e]}else var h=d;R[a].ia(h,decodeURIComponent(b))};Ie.prototype.Cb=function(a){"SETUP"==a?(this.send("tp","SETUP_ACK"),Fe(this.a)):"SETUP_ACK"==a&&Fe(this.a)};
Ie.prototype.send=function(a,b){b=encodeURIComponent(b);var c=b.length;if(G&&1800<c)for(var d=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^ta()).toString(36),e=0,f=0;e<c;f++){var h=b.substr(e,1800);e+=1800;Pe(this,a,h,d+(e>=c?"++":"+")+f)}else Pe(this,a,b)};
var Pe=function(a,b,c,d){if(G){var e=a.h().document.createElement("DIV"),f={src:null,srcdoc:null},h={onload:new Rb(Pb,"this.xpcOnload()"),sandbox:null},l={sandbox:""};var q={};for(var p in f)A(p.toLowerCase()==p,"Must be lower case"),q[p]=f[p];for(p in l)A(p.toLowerCase()==p,"Must be lower case"),q[p]=l[p];for(p in h){var k=p.toLowerCase();if(k in f)throw Error('Cannot override "'+k+'" attribute, got "'+p+'" with value "'+h[p]+'"');k in l&&delete q[k];q[p]=h[p]}f=null;h="";if(q)for(ia in q){if(!nc.test(ia))throw Error('Invalid attribute name "'+
ia+'".');p=q[ia];if(null!=p){l=ia;k=p;if(k instanceof Rb)k=Sb(k);else if("style"==l.toLowerCase()){p=void 0;if(!w(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);if(!(k instanceof H)){var Yd=k;k="";for(p in Yd){if(!/^[-_a-zA-Z0-9]+$/.test(p))throw Error("Name allows only [-_a-zA-Z0-9], got: "+p);var Fa=Yd[p];null!=Fa&&(Fa=u(Fa)?Ba(Fa,dc).join(" "):dc(Fa),k+=p+":"+Fa+";")}k?(p=k,A(!/[<>]/.test(p),"Forbidden characters in style string: "+
p),k=(new H).rb(k)):k=bc}k instanceof H&&k.constructor===H&&k.ad===ac?p=k.vb:(B("expected object of type SafeStyle, got '"+k+"' of type "+t(k)),p="type_error:SafeStyle");k=p}else{if(/^on/i.test(l))throw Error('Attribute "'+l+'" requires goog.string.Const value, "'+k+'" given.');if(l.toLowerCase()in oc)if(k instanceof Ub)k instanceof Ub&&k.constructor===Ub&&k.dd===Tb?k=k.ec:(B("expected object of type TrustedResourceUrl, got '"+k+"' of type "+t(k)),k="type_error:TrustedResourceUrl");else if(k instanceof
Wb)k=Xb(k);else if(r(k))k=$b(k).ea();else throw Error('Attribute "'+l+'" on tag "iframe" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.xa&&(k=k.ea());A(r(k)||ha(k),"String or number value expected, got "+typeof k+" with value: "+k);l=l+'="'+Ya(String(k))+'"';h+=" "+l}}var ia="<iframe"+h;h=void 0;null!=h?u(h)||(h=[h]):h=[];!0===Ob.iframe?(A(!h.length,"Void tag <iframe> does not allow content."),ia+=">"):(f=qc(h),ia+=">"+mc(f)+"</iframe>",f=f.Sa());(q=q&&q.dir)&&
(f=/^(ltr|rtl|auto)$/i.test(q)?0:null);q=pc(ia,f);if(rc[e.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+e.tagName+".");q=mc(q);if(sc())for(;e.lastChild;)e.removeChild(e.lastChild);e.innerHTML=q;e=e.childNodes[0];e.xpcOnload=Qe}else e=a.h().document.createElement("IFRAME"),yb?Je.push({timestamp:ta(),sd:e}):id(e,"load",Qe);q=e.style;q.visibility="hidden";q.width=e.style.height="0px";q.position="absolute";q=a.yd;q+="#"+a.a.name;a.Sc&&(q+=","+a.Sc);
q+="|"+b;d&&(q+="|"+d);q+=":"+c;e.src=q;a.h().document.body.appendChild(e);Oc("msg sent: "+q)},Qe=function(){Oc("iframe-load");vc(this)};Ie.prototype.f=function(){Ie.H.f.call(this);yb&&Le(0)};var V=function(a,b,c,d,e){S.call(this,c);this.a=a;this.U=e||2;A(1<=this.U);A(2>=this.U);this.Rc=b||"*";this.Ia=new Q(this);this.Z=new be(100,this.h());this.ub=!!d;this.D=new T;this.F=new T;this.w=new T;this.Nb=me();this.pa=null;this.ub?1==U(this.a)?ve(this.w,this.D):ve(this.w,this.F):(ve(this.w,this.D),2==this.U&&ve(this.w,this.F));ue(this.w,this.ac,this);this.w.M(!0);this.Ia.Xa(this.Z,"tick",this.Ya);K("NativeMessagingTransport created.  protocolVersion="+this.U+", oneSidedHandshake="+this.ub+", role="+
U(this.a))};y(V,S);V.prototype.G=null;V.prototype.Va=!1;V.prototype.Qa=1;var Re={};V.prototype.cb=0;
var Ue=function(a){var b=a.ma.data;if(!r(b))return!1;var c=b.indexOf("|"),d=b.indexOf(":");if(-1==c||-1==d)return!1;var e=b.substring(0,c);c=b.substring(c+1,d);b=b.substring(d+1);L(I.c,"messageReceived: channel="+e+", service="+c+", payload="+b);if(d=R[e])return d.ia(c,b,a.ma.origin),!0;d=Se(b)[0];for(var f in R){var h=R[f];if(1==U(h)&&!h.isConnected()&&"tp"==c&&("SETUP"==d||"SETUP_NTPV2"==d)&&Te(h,a.ma.origin))return ze(h,e),h.ia(c,b),!0}K('channel name mismatch; message ignored"');return!1};
V.prototype.Cb=function(a){var b=Se(a);a=b[1];switch(b[0]){case "SETUP_ACK":Ve(this,1);this.D.N||this.D.M(!0);break;case "SETUP_ACK_NTPV2":2==this.U&&(Ve(this,2),this.D.N||this.D.M(!0));break;case "SETUP":Ve(this,1);this.yb(1);break;case "SETUP_NTPV2":2==this.U&&(b=this.G,Ve(this,2),this.yb(2),1!=b&&null==this.pa||this.pa==a||(K("Sending SETUP and changing peer ID to: "+a),this.bb()),this.pa=a)}};
V.prototype.bb=function(){A(!(1==this.U&&2==this.G));2!=this.U||null!=this.G&&2!=this.G||this.send("tp","SETUP_NTPV2,"+this.Nb);null!=this.G&&1!=this.G||this.send("tp","SETUP")};V.prototype.yb=function(a){A(1!=this.U||2!=a,"Shouldn't try to send a v2 setup ack in v1 mode.");if(2!=this.U||null!=this.G&&2!=this.G||2!=a){if(null!=this.G&&1!=this.G||1!=a)return;this.send("tp","SETUP_ACK")}else this.send("tp","SETUP_ACK_NTPV2");this.F.N||this.F.M(!0)};
var Ve=function(a,b){b>a.G&&(a.G=b);1==a.G&&(a.F.N||a.ub||a.F.M(!0),a.pa=null)};g=V.prototype;g.connect=function(){var a=this.h(),b=pa(a),c=Re[b];ha(c)||(c=0);0==c&&id(a.postMessage?a:a.document,"message",Ue,!1,V);Re[b]=c+1;this.Va=!0;this.Ya()};g.Ya=function(){var a=0==U(this.a);this.ub&&a||this.a.isConnected()||this.la?this.Z.stop():(this.Z.start(),this.bb())};
g.send=function(a,b){var c=this.a.R;c?(this.send=function(a,b){var d=this,e=this.a.name;this.cb=ce(function(){d.cb=0;try{var f=c.postMessage?c:c.document;if(f.postMessage)f.postMessage(e+"|"+a+":"+b,d.Rc),L(I.c,"send(): service="+a+" payload="+b+" to hostname="+d.Rc);else{var h=I.c;h&&h.ra("Peer window had no postMessage function.",void 0)}}catch(p){(f=I.c)&&f.ra("Error performing postMessage, ignoring.",p)}},0)},this.send(a,b)):L(I.c,"send(): window not ready")};
g.ac=function(){Fe(this.a,1==this.U||1==this.G?200:void 0)};g.f=function(){if(this.Va){var a=this.h(),b=pa(a),c=Re[b];Re[b]=c-1;1==c&&pd(a.postMessage?a:a.document,"message",Ue,!1,V)}this.cb&&(m.clearTimeout(this.cb),this.cb=0);N(this.Ia);delete this.Ia;N(this.Z);delete this.Z;this.D.cancel();delete this.D;this.F.cancel();delete this.F;this.w.cancel();delete this.w;delete this.send;V.H.f.call(this)};var Se=function(a){a=a.split(",");a[1]=a[1]||null;return a};var We=function(a,b){S.call(this,b);this.a=a;this.sc=a.at||"";this.Vc=a.rat||"";a=this.h();if(!a.nix_setup_complete)try{a.execScript("Class GCXPC____NIXVBS_wrapper\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport.GCXPC____NIXJS_handle_message(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport.GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function GCXPC____NIXVBS_get_wrapper(transport, auth)\nDim wrap\nSet wrap = New GCXPC____NIXVBS_wrapper\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function",
"vbscript"),a.nix_setup_complete=!0}catch(c){J(I.c,"exception caught while attempting global setup: "+c)}this.GCXPC____NIXJS_handle_message=this.rd;this.GCXPC____NIXJS_create_channel=this.jd};y(We,S);g=We.prototype;g.Qa=6;g.Ma=!1;g.oa=null;g.connect=function(){0==U(this.a)?this.pc():this.oc()};
g.pc=function(){if(!this.Ma){var a=this.a.Ka;try{a.contentWindow.opener=(0,this.h().GCXPC____NIXVBS_get_wrapper)(this,this.sc),this.Ma=!0}catch(b){J(I.c,"exception caught while attempting setup: "+b)}this.Ma||this.h().setTimeout(x(this.pc,this),100)}};
g.oc=function(){if(!this.Ma){try{var a=this.h().opener;if(a&&"GCXPC____NIXVBS_container"in a){this.oa=a;if(this.oa.GetAuthToken()!=this.Vc){J(I.c,"Invalid auth token from other party");return}this.oa.CreateChannel((0,this.h().GCXPC____NIXVBS_get_wrapper)(this,this.sc));this.Ma=!0;Fe(this.a)}}catch(b){J(I.c,"exception caught while attempting setup: "+b);return}this.Ma||this.h().setTimeout(x(this.oc,this),100)}};
g.jd=function(a){"unknown"==typeof a&&"GCXPC____NIXVBS_container"in a||J(I.c,"Invalid NIX channel given to createChannel_");this.oa=a;this.oa.GetAuthToken()!=this.Vc?J(I.c,"Invalid auth token from other party"):Fe(this.a)};g.rd=function(a,b){this.h().setTimeout(x(function(){this.a.ia(a,b)},this),1)};g.send=function(a,b){"unknown"!==typeof this.oa&&J(I.c,"NIX channel not connected");this.oa.SendMessage(a,b)};g.f=function(){We.H.f.call(this);this.oa=null};var Xe=function(a,b){this.o={};this.g=[];this.hb=this.j=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};g=Xe.prototype;g.O=function(){Ye(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.o[this.g[b]]);return a};g.da=function(){Ye(this);return this.g.concat()};g.Ha=function(a){return Ze(this.o,a)};g.clear=function(){this.o={};this.hb=this.j=this.g.length=0};
g.remove=function(a){return Ze(this.o,a)?(delete this.o[a],this.j--,this.hb++,this.g.length>2*this.j&&Ye(this),!0):!1};var Ye=function(a){if(a.j!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Ze(a.o,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.j!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],Ze(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}};g=Xe.prototype;g.get=function(a,b){return Ze(this.o,a)?this.o[a]:b};
g.set=function(a,b){Ze(this.o,a)||(this.j++,this.g.push(a),this.hb++);this.o[a]=b};g.addAll=function(a){if(a instanceof Xe)for(var b=a.da(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};g.forEach=function(a,b){for(var c=this.da(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};g.clone=function(){return new Xe(this)};
g.Ib=function(a){Ye(this);var b=0,c=this.hb,d=this,e=new he;e.next=function(){if(c!=d.hb)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)throw ge;var e=d.g[b++];return a?e:d.o[e]};return e};var Ze=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var $e=function(a){if(a.O&&"function"==typeof a.O)return a.O();if(r(a))return a.split("");if(ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Na(a)},af=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(ma(a)||r(a))Aa(a,b,c);else{if(a.da&&"function"==typeof a.da)var d=a.da();else if(a.O&&"function"==typeof a.O)d=void 0;else if(ma(a)||r(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=$e(a);f=e.length;for(var h=
0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};var bf=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,cf=function(a){var b=a.match(bf);a=b[1];var c=b[2],d=b[3];b=b[4];var e="";a&&(e+=a+":");d&&(e+="//",c&&(e+=c+"@"),e+=d,b&&(e+=":"+b));return e},df=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var W=function(a){this.ba=this.Da=this.qa="";this.Oa=null;this.ua=this.$="";this.P=this.td=!1;if(a instanceof W){this.P=n(void 0)?void 0:a.P;ef(this,a.qa);var b=a.Da;X(this);this.Da=b;b=a.ba;X(this);this.ba=b;ff(this,a.Oa);b=a.$;X(this);this.$=b;gf(this,a.C.clone());a=a.ua;X(this);this.ua=a}else a&&(b=String(a).match(bf))?(this.P=!1,ef(this,b[1]||"",!0),a=b[2]||"",X(this),this.Da=hf(a),a=b[3]||"",X(this),this.ba=hf(a,!0),ff(this,b[4]),a=b[5]||"",X(this),this.$=hf(a,!0),gf(this,b[6]||"",!0),a=b[7]||
"",X(this),this.ua=hf(a)):(this.P=!1,this.C=new jf(null,this.P))};
W.prototype.toString=function(){var a=[],b=this.qa;b&&a.push(kf(b,lf,!0),":");var c=this.ba;if(c||"file"==b)a.push("//"),(b=this.Da)&&a.push(kf(b,lf,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Oa,null!=c&&a.push(":",String(c));if(c=this.$)this.ba&&"/"!=c.charAt(0)&&a.push("/"),a.push(kf(c,"/"==c.charAt(0)?mf:nf,!0));(c=this.C.toString())&&a.push("?",c);(c=this.ua)&&a.push("#",kf(c,of));return a.join("")};
W.prototype.resolve=function(a){var b=this.clone(),c=!!a.qa;c?ef(b,a.qa):c=!!a.Da;if(c){var d=a.Da;X(b);b.Da=d}else c=!!a.ba;c?(d=a.ba,X(b),b.ba=d):c=null!=a.Oa;d=a.$;if(c)ff(b,a.Oa);else if(c=!!a.$){if("/"!=d.charAt(0))if(this.ba&&!this.$)d="/"+d;else{var e=b.$.lastIndexOf("/");-1!=e&&(d=b.$.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],h=0;h<e.length;){var l=e[h++];"."==l?d&&h==e.length&&f.push(""):
".."==l?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&h==e.length&&f.push("")):(f.push(l),d=!0)}d=f.join("/")}else d=e}c?(X(b),b.$=d):c=""!==a.C.toString();c?gf(b,a.C.clone()):c=!!a.ua;c&&(a=a.ua,X(b),b.ua=a);return b};W.prototype.clone=function(){return new W(this)};
var ef=function(a,b,c){X(a);a.qa=c?hf(b,!0):b;a.qa&&(a.qa=a.qa.replace(/:$/,""))},ff=function(a,b){X(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.Oa=b}else a.Oa=null},gf=function(a,b,c){X(a);b instanceof jf?(a.C=b,a.C.jc(a.P)):(c||(b=kf(b,pf)),a.C=new jf(b,a.P))};W.prototype.getQuery=function(){return this.C.toString()};W.prototype.removeParameter=function(a){X(this);this.C.remove(a);return this};
var X=function(a){if(a.td)throw Error("Tried to modify a read-only Uri");};W.prototype.jc=function(a){this.P=a;this.C&&this.C.jc(a)};
var hf=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},kf=function(a,b,c){return r(a)?(a=encodeURI(a).replace(b,qf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},qf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},lf=/[#\/\?@]/g,nf=/[#\?:]/g,mf=/[#\?]/g,pf=/[#\?@]/g,of=/#/g,jf=function(a,b){this.j=this.i=null;this.L=a||null;this.P=!!b},rf=function(a){a.i||(a.i=new Xe,a.j=0,a.L&&df(a.L,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};g=jf.prototype;g.add=function(a,b){rf(this);this.L=null;a=sf(this,a);var c=this.i.get(a);c||this.i.set(a,c=[]);c.push(b);this.j=xa(this.j)+1;return this};g.remove=function(a){rf(this);a=sf(this,a);return this.i.Ha(a)?(this.L=null,this.j=xa(this.j)-this.i.get(a).length,this.i.remove(a)):!1};g.clear=function(){this.i=this.L=null;this.j=0};g.Ha=function(a){rf(this);a=sf(this,a);return this.i.Ha(a)};
g.forEach=function(a,b){rf(this);this.i.forEach(function(c,d){Aa(c,function(c){a.call(b,c,d,this)},this)},this)};g.da=function(){rf(this);for(var a=this.i.O(),b=this.i.da(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};g.O=function(a){rf(this);var b=[];if(r(a))this.Ha(a)&&(b=Ha(b,this.i.get(sf(this,a))));else{a=this.i.O();for(var c=0;c<a.length;c++)b=Ha(b,a[c])}return b};
g.set=function(a,b){rf(this);this.L=null;a=sf(this,a);this.Ha(a)&&(this.j=xa(this.j)-this.i.get(a).length);this.i.set(a,[b]);this.j=xa(this.j)+1;return this};g.get=function(a,b){if(!a)return b;a=this.O(a);return 0<a.length?String(a[0]):b};
g.toString=function(){if(this.L)return this.L;if(!this.i)return"";for(var a=[],b=this.i.da(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.O(d);for(var f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}}return this.L=a.join("&")};g.clone=function(){var a=new jf;a.L=this.L;this.i&&(a.i=this.i.clone(),a.j=this.j);return a};var sf=function(a,b){b=String(b);a.P&&(b=b.toLowerCase());return b};
jf.prototype.jc=function(a){a&&!this.P&&(rf(this),this.L=null,this.i.forEach(function(a,c){var b=c.toLowerCase();c!=b&&(this.remove(c),this.remove(b),0<a.length&&(this.L=null,this.i.set(sf(this,b),Ia(a)),this.j=xa(this.j)+a.length))},this));this.P=a};jf.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)af(arguments[b],function(a,b){this.add(b,a)},this)};var uf=function(a,b){ie.call(this);for(var c=0,d;d=ke[c];c++)if(d in a&&!/^https?:\/\//.test(a[d]))throw Error("URI "+a[d]+" is invalid for field "+d);this.m=a;this.name=this.m.cn||me();this.X=b||ua||(ua=new wc);this.mb=[];this.dc=new Q(this);a.lpu=a.lpu||cf(this.X.h().location.href)+"/robots.txt";a.ppu=a.ppu||cf(a.pu||"")+"/robots.txt";R[this.name]=this;rd(window,"unload",tf)||hd(window,"unload",tf);K("CrossPageChannel created: "+this.name)};y(uf,ie);var vf=/^%*tp$/,wf=/^%+tp$/;g=uf.prototype;
g.ka=null;g.Ba=null;g.I=null;g.l=1;g.isConnected=function(){return 2==this.l};g.R=null;g.Ka=null;g.connect=function(a){this.Lb=a||la;3==this.l&&(this.l=1);this.Ba?ue(this.Ba,this.yc):this.yc()};
g.yc=function(){K("continueConnection_()");this.Ba=null;if(this.m.ifrid){var a=this.m.ifrid;this.Ka=r(a)?this.X.Ra.getElementById(a):a}this.Ka&&((a=this.Ka.contentWindow)||(a=window.frames[this.m.ifrid]),this.R=a);if(!this.R){if(window==window.top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");this.R=window.parent}if(!this.I){if(!this.m.tp){a=this.m;if(v(document.postMessage)||v(window.postMessage)||G&&window.postMessage)var b=1;else if(xb)b=2;else if(G&&this.m.pru)b=
3;else{var c;if(c=G){c=!1;try{b=window.opener,window.opener={},c=sb(window,"opener"),window.opener=b}catch(d){}}b=c?6:0}a.tp=b}if(v(this.m.tp))this.I=new this.m.tp(this,this.X);else switch(this.m.tp){case 1:this.I=new V(this,this.m.ph,this.X,!!this.m.osh,this.m.nativeProtocolVersion||2);break;case 6:this.I=new We(this,this.X);break;case 2:this.I=new Ge(this,this.X);break;case 3:this.I=new Ie(this,this.X);break;case 7:if(a=this.R)try{a=window.document.domain==this.R.document.domain}catch(d){a=!1}a?
this.I=new Ae(this,this.X):K("DirectTransport not supported for this window, peer window in different security context or not set yet.")}if(this.I)K("Transport created: "+this.I.getName());else throw Error("CrossPageChannel: No suitable transport found! You may try injecting a Transport constructor directly via the channel config object.");}for(this.I.connect();0<this.mb.length;)this.mb.shift()()};
g.close=function(){this.Ba&&(this.Ba.cancel(),this.Ba=null);this.mb.length=0;this.dc.ab();this.l=3;N(this.I);this.Lb=this.I=null;N(this.ka);this.ka=null;K('Channel "'+this.name+'" closed')};var Fe=function(a,b){a.isConnected()||a.ka&&a.ka.Vb()||(a.l=2,K('Channel "'+a.name+'" connected'),N(a.ka),n(b)?(a.ka=new de(a.Lb,b),a.ka.start()):(a.ka=null,a.Lb()))};
uf.prototype.send=function(a,b){if(this.isConnected()){try{var c=!!this.R&&!this.R.closed}catch(d){c=!1}c?(w(b)&&(b=(new xc).Ab(b)),this.I.send(xf(a),b)):(J(I.c,"Peer has disappeared."),this.close())}else J(I.c,"Can't send. Channel not connected.")};
uf.prototype.ia=function(a,b,c){if(this.Ba)this.mb.push(x(this.ia,this,a,b,c));else if(Te(this,c))if(this.la||3==this.l)(b=I.c)&&b.ra("CrossPageChannel::xpcDeliver(): Channel closed.",void 0);else if(a&&"tp"!=a)if(this.isConnected()){if(c=a.replace(/%[0-9a-f]{2}/gi,decodeURIComponent),c=wf.test(c)?c.substring(1):c,a=this.ic[c],a||(this.Bc?a={M:sa(this.Bc,c),Nc:w(b)}:((a=this.c)&&a.ra('Unknown service name "'+c+'"',void 0),a=null)),a){a:{var d=a.Nc;if(d&&r(b))try{var e=JSON.parse(b);break a}catch(f){(e=
this.c)&&e.ra("Expected JSON payload for "+c+', was "'+b+'"',void 0);e=null;break a}else if(!d&&!r(b)){e=(new xc).Ab(b);break a}e=b}null!=e&&a.M(e)}}else K("CrossPageChannel::xpcDeliver(): Not connected.");else this.I.Cb(b);else(b=I.c)&&b.ra('Message received from unapproved origin "'+c+'" - rejected.',void 0)};
var xf=function(a){vf.test(a)&&(a="%"+a);return a.replace(/[%:|]/g,encodeURIComponent)},U=function(a){var b=a.m.role;return ha(b)?b:window.parent==a.R?1:0},ze=function(a,b){L(I.c,"changing channel name to "+b);delete R[a.name];a.name=b;R[b]=a},Te=function(a,b){var c=a.m.ph;return/^[\s\xa0]*$/.test(null==b?"":String(b))||/^[\s\xa0]*$/.test(null==c?"":String(c))||b==a.m.ph};uf.prototype.f=function(){this.close();this.Ka=this.R=null;delete R[this.name];N(this.dc);delete this.dc;uf.H.f.call(this)};
var tf=function(){for(var a in R)N(R[a])};var yf=function(){this.Uc=ta()},zf=null;yf.prototype.set=function(a){this.Uc=a};yf.prototype.reset=function(){this.set(ta())};yf.prototype.get=function(){return this.Uc};var Af=function(){zf||(zf=new yf)},Bf=function(){zf||(zf=new yf)};y(Bf,Af);var Cf=function(){};Cf.prototype.vc=null;var Ef=function(a){var b;(b=a.vc)||(b={},Df(a)&&(b[0]=!0,b[1]=!0),b=a.vc=b);return b};var Ff,Gf=function(){};y(Gf,Cf);var Hf=function(a){return(a=Df(a))?new ActiveXObject(a):new XMLHttpRequest},Df=function(a){if(!a.Ic&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.Ic=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.Ic};Ff=new Gf;var Y=function(a){O.call(this);this.headers=new Xe;this.Hb=a||null;this.ja=!1;this.Gb=this.b=null;this.Wa=this.Kc=this.sb="";this.ya=this.Tb=this.qb=this.Ob=!1;this.eb=0;this.Bb=null;this.Wc="";this.Eb=this.zd=this.nc=!1};y(Y,O);var If=/^https?$/i,Jf=["POST","PUT"],Kf=[];Y.prototype.hd=function(){this.Mb();Ga(Kf,this)};
Y.prototype.send=function(a,b,c,d){if(this.b)throw Error("[goog.net.XhrIo] Object is active with another request="+this.sb+"; newUri="+a);b=b?b.toUpperCase():"GET";this.sb=a;this.Wa="";this.Kc=b;this.Ob=!1;this.ja=!0;this.b=this.Hb?Hf(this.Hb):Hf(Ff);this.Gb=this.Hb?Ef(this.Hb):Ef(Ff);this.b.onreadystatechange=x(this.Qc,this);this.zd&&"onprogress"in this.b&&(this.b.onprogress=x(function(a){this.Pc(a,!0)},this),this.b.upload&&(this.b.upload.onprogress=x(this.Pc,this)));try{L(this.T,Z(this,"Opening Xhr")),
this.Tb=!0,this.b.open(b,String(a),!0),this.Tb=!1}catch(f){L(this.T,Z(this,"Error opening Xhr: "+f.message));this.nb(5,f);return}a=c||"";var e=this.headers.clone();d&&af(d,function(a,b){e.set(b,a)});d=Ea(e.da());c=m.FormData&&a instanceof m.FormData;!(0<=za(Jf,b))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.b.setRequestHeader(b,a)},this);this.Wc&&(this.b.responseType=this.Wc);"withCredentials"in this.b&&this.b.withCredentials!==this.nc&&
(this.b.withCredentials=this.nc);try{Lf(this),0<this.eb&&(this.Eb=Mf(this.b),L(this.T,Z(this,"Will abort after "+this.eb+"ms if incomplete, xhr2 "+this.Eb)),this.Eb?(this.b.timeout=this.eb,this.b.ontimeout=x(this.Yc,this)):this.Bb=ce(this.Yc,this.eb,this)),L(this.T,Z(this,"Sending request")),this.qb=!0,this.b.send(a),this.qb=!1}catch(f){L(this.T,Z(this,"Send error: "+f.message)),this.nb(5,f)}};
var Mf=function(a){return G&&Lb(9)&&ha(a.timeout)&&n(a.ontimeout)},Da=function(a){return"content-type"==a.toLowerCase()};Y.prototype.Yc=function(){"undefined"!=typeof fa&&this.b&&(this.Wa="Timed out after "+this.eb+"ms, aborting",L(this.T,Z(this,this.Wa)),this.dispatchEvent("timeout"),this.abort(8))};Y.prototype.nb=function(a,b){this.ja=!1;this.b&&(this.ya=!0,this.b.abort(),this.ya=!1);this.Wa=b;Nf(this);Of(this)};var Nf=function(a){a.Ob||(a.Ob=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
Y.prototype.abort=function(){this.b&&this.ja&&(L(this.T,Z(this,"Aborting")),this.ja=!1,this.ya=!0,this.b.abort(),this.ya=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Of(this))};Y.prototype.f=function(){this.b&&(this.ja&&(this.ja=!1,this.ya=!0,this.b.abort(),this.ya=!1),Of(this,!0));Y.H.f.call(this)};Y.prototype.Qc=function(){this.la||(this.Tb||this.qb||this.ya?Pf(this):this.wd())};Y.prototype.wd=function(){Pf(this)};
var Pf=function(a){if(a.ja&&"undefined"!=typeof fa)if(a.Gb[1]&&4==Qf(a)&&2==Rf(a))L(a.T,Z(a,"Local request error detected and ignored"));else if(a.qb&&4==Qf(a))ce(a.Qc,0,a);else if(a.dispatchEvent("readystatechange"),4==Qf(a)){L(a.T,Z(a,"Request complete"));a.ja=!1;try{if(Sf(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{try{var b=2<Qf(a)?a.b.statusText:""}catch(c){L(a.T,"Can not get status: "+c.message),b=""}a.Wa=b+" ["+Rf(a)+"]";Nf(a)}}finally{Of(a)}}};
Y.prototype.Pc=function(a,b){A("progress"===a.type,"goog.net.EventType.PROGRESS is of the same type as raw XHR progress.");this.dispatchEvent(Tf(a,"progress"));this.dispatchEvent(Tf(a,b?"downloadprogress":"uploadprogress"))};
var Tf=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}},Of=function(a,b){if(a.b){Lf(a);var c=a.b,d=a.Gb[0]?la:null;a.b=null;a.Gb=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){J(a.T,"Problem encountered resetting onreadystatechange: "+e.message)}}},Lf=function(a){a.b&&a.Eb&&(a.b.ontimeout=null);a.Bb&&(m.clearTimeout(a.Bb),a.Bb=null)};Y.prototype.Vb=function(){return!!this.b};
var Sf=function(a){var b=Rf(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.sb).match(bf)[1]||null,!a&&m.self&&m.self.location&&(a=m.self.location.protocol,a=a.substr(0,a.length-1)),b=!If.test(a?a.toLowerCase():"");c=b}return c},Qf=function(a){return a.b?a.b.readyState:0},Rf=function(a){try{return 2<Qf(a)?a.b.status:-1}catch(b){return-1}},Uf=function(a){try{return a.b?a.b.responseText:""}catch(b){return L(a.T,
"Can not get responseText: "+b.message),""}};Y.prototype.getResponseHeader=function(a){if(this.b&&4==Qf(this))return a=this.b.getResponseHeader(a),null===a?void 0:a};Y.prototype.getAllResponseHeaders=function(){return this.b&&4==Qf(this)?this.b.getAllResponseHeaders()||"":""};var Z=function(a,b){return b+" ["+a.Kc+" "+a.sb+" "+Rf(a)+"]"};new O;new Bf;var Vf=function(a){this.o=new Xe;a&&this.addAll(a)},Wf=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+pa(a):b.substr(0,1)+a};g=Vf.prototype;g.add=function(a){this.o.set(Wf(a),a)};g.addAll=function(a){a=$e(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};g.ab=function(a){a=$e(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};g.remove=function(a){return this.o.remove(Wf(a))};g.clear=function(){this.o.clear()};g.contains=function(a){return this.o.Ha(Wf(a))};g.O=function(){return this.o.O()};
g.clone=function(){return new Vf(this)};g.Ib=function(){return this.o.Ib(!1)};(function(){if(Ab){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(E))?a[1]:"0"}return zb?(a=/10[_.][0-9_.]+/,(a=a.exec(E))?a[0].replace(/_/g,"."):"10"):Bb?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(E))?a[1]:""):Cb||Db||Eb?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(E))?a[1].replace(/_/g,"."):""):""})();new Vf([1,2,3]);new Vf([1,2]);var Xf=new nb,Yf=new D;C(Yf,1,3);C(Yf,2,2);C(Xf,1,Yf);var Zf=new D;C(Zf,1,3);C(Zf,2,2);var $f=new D;C($f,1,3);C($f,2,2);var ag=function(a,b,c,d,e){a=new W(a);0!=b&&(X(a),a.C.set("authuser",b));null!=c&&(X(a),a.C.set("pageId",c));null!=d&&(X(a),a.C.set("service",d));this.Cd=a.toString();this.wa=e;this.vd=0};ag.prototype.start=function(){};ag.prototype.send=function(a,b,c){var d=new W(this.Cd);for(h in c){var e=h,f=c[h];X(d);d.C.set(e,f)}c=d.toString();d=x(this.Hc,this,this.vd++);var h=new Y;Kf.push(h);d&&h.Xa("complete",d);h.Xb("ready",h.hd);h.nc=!0;h.send(c,"POST",a,b)};
ag.prototype.Hc=function(a,b){b=b.target;Sf(b)?this.wa.ta.send("ss",[a]):(b=Uf(b),this.wa.ta.send("sf",[a,b]))};var bg=function(a,b,c,d,e){this.qd=new ag(a,b,c,d,this);a=new W(e||window.location.href);this.Hd=JSON.parse(a.C.get("xpc")||"");this.ta=null};bg.prototype.Ub=function(){this.ta=new uf(this.Hd);var a=x(bg.prototype.send,this);this.ta.ic.s={M:a,Nc:!0};this.ta.connect()};bg.prototype.send=function(a){this.qd.send(a[0],a[1],a[2])};bg.prototype.Hc=function(a,b){b=b.target;Sf(b)?this.ta.send("ss",[a]):this.ta.send("sf",[a,Uf(b)])};bg.prototype.init=bg.prototype.Ub;ja("invalidation.XpcSenderServer",bg,void 0);
